#!/usr/bin/env python3
"""
Count the sequence lengths in several fasta files.
"""
import sys
import subprocess
from multiprocessing import Pool

def count_prots(infile):
    handle = open(infile,'r')
    rawfile = handle.read()
    handle.close()
    outfilename = infile + ".counts.csv"
    outfile = open(outfilename, 'w')
    seqs = rawfile.split('>')
    for line in seqs:
        if line == '':
            pass
        else:
            linesep = line.split('\n')
            outfile.write(linesep[0] +',')
            seq = ''.join(linesep[1:])
            outfile.write(str(len(seq)) +'\n')        
    outfile.close()

def add(args):
    (first) = args
    count_prots(first)

def main():

    try:
        infilename = sys.argv[1]
        procs = int(sys.argv[2])
    except:
        print("""
    Count the sequence lengths in several fasta files.
    Usage:
    seqlen infile CPUs 
        """)
        sys.exit()
        
    handle = open(infilename, 'r')
    infile = handle.read().split('\n')[:-1]
    handle.close()
     
    count_pool = Pool(procs)
    work = []
    for i in infile:
        work.append((i))
    count_pool.map(add, work)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.exit("\n(Terminating due to user interrupt signal)")
